#!/bin/sh

# run main function from {class} and record timing and git revision to results/{className}_results.txt

FILE="results/$1_results.txt"

echo "results file: $FILE"

mkdir -p results
echo "=========================================" >> $FILE
echo "$(date +"%F_%T") (`git log --oneline -1`)" >> $FILE
git status --porcelain >> $FILE
echo "-----------------------------------------" >> $FILE
echo "$ $@" >> $FILE
(./run $@ < /dev/stdin) 2>&1 | tee -a $FILE
